{
 "title": "PV Cham",
 "tags": [
  "favoriten",
  "location"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Location", "query": "cham, casacham, eich" },
   { "name": "Location_gross", "query": "Cham" },
   { "name": "battery", "query": "19.32, 22.0" },
   {
    "name": "link",
    "query": "https://tom.li/grafana/d/ZDTJEXvVk/pv-cham"
   }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:W" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n  meter{location=\"$Location\",position=\"grid\",type=\"gauge\"} + \n  scalar(sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"} >=0)) - \n  scalar(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}*-1)\n,0)",
     "legendFormat": "{{position}} / {{location}}"
    }
   ]
  },
  {
   "title": "EW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meter{position=\"grid\",type=\"gauge\",location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:W" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum({position=\"generator\",type=\"gauge\",location=~\"$Location\"} >=0)",
     "legendFormat": "PV {{description}}"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:W" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}*-1",
     "legendFormat": "PV"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor{location=\"$Location\",position=\"battery\",type=\"percent\"}",
     "legendFormat": "SOC"
    },
    {
     "expr": "scalar(sensor{location=\"$Location\",position=\"battery\",type=\"percent\"})*19.32/100",
     "legendFormat": "Kapazität"
    }
   ]
  },
  {
   "title": "Wärmepumpe",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:W" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "abs(meter{position=\"device\", description=\"Wärmepumpe\",type=\"gauge\",location=\"$Location\"})",
     "legendFormat": "{{position}} / {{location}}"
    }
   ]
  },
  {
   "title": "Aussentemp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sensor{kind=\"outdoor\",type=\"temp\", location=~\"$Location\"})",
     "legendFormat": "Temp"
    }
   ]
  },
  {
   "title": "PV",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "clamp_min(\n  meter{location=\"$Location\",position=\"grid\",type=\"gauge\"} + \n  scalar(sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"} >=0)) - \n  scalar(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}*-1)\n,0)",
     "legendFormat": "Verbrauch"
    },
    {
     "expr": "sum(clamp_min(meter{location=\"$Location\",position=\"grid\",type=\"gauge\"}, 0))",
     "legendFormat": "Bezug"
    },
    {
     "expr": "sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"} >=0)",
     "legendFormat": "PV"
    },
    {
     "expr": "sum(clamp_max(meter{location=\"$Location\",position=\"grid\",type=\"gauge\"}, 0) *-1)",
     "legendFormat": "Einspeisung"
    },
    {
     "expr": "abs(meter{location=\"$Location\",position=\"device\",type=\"gauge\",description=\"Wärmepumpe\"})",
     "legendFormat": "WP"
    },
    { "target": [ "sun_altitude" ] },
    {
     "expr": "sensor{location=\"$Location\",position=\"battery\",type=\"percent\"}",
     "legendFormat": "Batterie"
    },
    {
     "expr": "clamp_min(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"},0)",
     "legendFormat": "Batteriebezug"
    },
    {
     "expr": "sum(max_over_time(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}[$__range]))",
     "legendFormat": "PV Peak"
    }
   ]
  },
  {
   "title": "Verbrauch Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[$__range]))/1000 \n- sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[$__range]))/1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}>0)[$__range:5s]\n)  / 720 / 1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}<0)[$__range:5s]\n)  / 720 / 1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[$__range:5s]\n)  / 720 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bezug Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[$__range])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[$__range:5s]\n)  / 720 / 1000",
     "legendFormat": "Produktion"
    }
   ]
  },
  {
   "title": "Einspeisung Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[$__range])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eigenverbrauch Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[$__range:5s]\n)  / 720 / 1000\n- sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[$__range]))/1000 >=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wärmepumpe Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(meter{description=\"Wärmepumpe\",location=\"$Location\",position=\"device\",type=\"counter\"}[$__range])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} >0)[$__range:5s]\n )  / 720 / 1000\n)\n\n",
     "legendFormat": "Bezug"
    },
    {
     "expr": "max(\n  sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} <0)[$__range:5s]\n  )  / 720 / 1000 *-1\n)",
     "legendFormat": "Ladung"
    }
   ]
  },
  {
   "title": "Boiler",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor{type=\"temp\", kind=\"boiler\", position=\"boiler\", location=~\"$Location\"}",
     "legendFormat": "Boiler"
    }
   ]
  },
  {
   "title": "PV Total",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000",
     "legendFormat": "Produktion"
    },
    {
     "expr": "sum(increase(meter{position=\"generator\",type=\"counter\",direction=\"out\",location=\"$Location\"}[1d] offset -1d)  / 1000 >=0)\n",
     "legendFormat": "Produktion old"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[1d] offset -1d))/1000 \n- sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[1d] offset -1d))/1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}<0)[1d:5s] offset -1d\n)  / 720 / 1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000\n\n-sum(increase((meter{description=\"Wärmepumpe\",location=\"$Location\",position=\"device\",type=\"counter\"} or vector(0))[1d:5s] offset -1d)) / 1000",
     "legendFormat": "Haushalt"
    },
    {
     "expr": "sum(increase(meter{description=\"Wärmepumpe\",location=\"$Location\",position=\"device\",type=\"counter\"}[1d] offset -1d)) / 1000\n\n",
     "legendFormat": "Wärmepumpe"
    }
   ]
  },
  {
   "title": "PV Total / Verbrauch Total",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000",
     "legendFormat": "PV"
    },
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[1d] offset -1d))/1000 \n- sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[1d] offset -1d))/1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}<0)[1d:5s] offset -1d\n)  / 720 / 1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000",
     "legendFormat": "Verbrauch"
    },
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[1d] offset -1d)) / 1000",
     "legendFormat": "Bezug"
    }
   ]
  },
  {
   "title": "PV Total / Verwendung",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000\n\n- sum(increase(meter{location=\"$Location\",position=\"grid\",type=\"counter\",direction=\"out\"}[1d] offset -1d)/1000)\n- min(\n sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} <0)[1d:5s] offset -1d\n )  / 720 / 1000 *-1\n) >=0",
     "legendFormat": "PV Direktverbrauch"
    },
    {
     "expr": "min(\n sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} <0)[1d:5s] offset -1d\n )  / 720 / 1000 *-1\n)",
     "legendFormat": "Batterieladung"
    },
    {
     "expr": "sum(increase(meter{location=\"$Location\",position=\"grid\",type=\"counter\",direction=\"out\"}[1d] offset -1d)/1000)",
     "legendFormat": "Einspeisung"
    }
   ]
  },
  {
   "title": "Verbrauch Total / Herkunft",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "targets": [
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[1d] offset -1d)) / 1000",
     "legendFormat": "Bezug Netz"
    },
    {
     "expr": "sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[1d] offset -1d))/1000 \n- sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[1d] offset -1d))/1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"})[1d:5s] offset -1d\n)  / 720 / 1000\n+ sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[1d:5s] offset -1d\n)  / 720 / 1000\n-\nsum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[1d] offset -1d)) / 1000\n-\nmax(\n sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} >0)[1d:5s] offset -1d\n )  / 720 / 1000\n)\n>=0\n",
     "legendFormat": "PV Direktverbrauch"
    },
    {
     "expr": "max(\n sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} >0)[1d:5s] offset -1d\n )  / 720 / 1000\n)",
     "legendFormat": "Batteriebezug"
    }
   ]
  },
  {
   "title": "Bezug Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "((sum(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}) - sum(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"} offset $__interval > 0)) /1000) * scalar(tarif{location=\"$Location\",type=\"bezug\"})/100  >=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Einspeisung Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "((sum(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}) - sum(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"} offset $__interval > 0)) /1000  ) * scalar(tarif{location=\"$Location\",type=\"einspeisung\"})/100 >=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amortisation Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n (last_over_time(sum((meter{location=\"$Location\",position=\"grid\",type=\"gauge\"}<0) or vector(0))[30s:10s])\n * scalar(last_over_time((sum((tarif {location=\"$Location\",type=\"bezug\"}>0) or vector(0))/100)[30s:10s])))[$__range:5s]\n) / 720 /1000",
     "legendFormat": "A"
    },
    {
     "expr": "sum_over_time(\n (last_over_time(sum((meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}>0) or vector(0))[30s:10s])\n * scalar(last_over_time((sum((tarif {location=\"$Location\",type=\"bezug\"}>0)/100) or vector(0))[30s:10s])))[$__range:5s]\n) / 720 /1000",
     "legendFormat": "B"
    },
    {
     "expr": "+sum_over_time(\n (last_over_time(sum((meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}<0) or vector(0))[30s:10s]) \n * scalar(last_over_time((sum((tarif {location=\"$Location\",type=\"bezug\"}>0)/100) or vector(0))[30s:10s])))[$__range:5s]\n) / 720 /1000",
     "legendFormat": "C"
    },
    {
     "expr": "+sum_over_time(\n sum((last_over_time(sum((meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0) or vector(0))[30s:10s])) \n * scalar(last_over_time((sum((tarif {location=\"$Location\",type=\"bezug\"}>0)/100) or vector(0))[30s:10s])))[$__range:5s]\n) / 720 /1000",
     "legendFormat": "D"
    },
    {
     "expr": "sum_over_time(\n (last_over_time(sum((meter{location=\"$Location\",position=\"grid\",type=\"gauge\"}<0) or vector(0))[30s:10s]) * -1\n * scalar(last_over_time((sum((tarif {location=\"$Location\",type=\"einspeisung\"}>0)/100) or vector(0))[30s:10s])))[$__range:5s]\n) / 720 /1000 ",
     "legendFormat": "E"
    }
   ]
  },
  {
   "title": "Amortisation Batterie",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}>0) * scalar(tarif{location=\"$Location\",type=\"bezug\"})/100>0)[$__range:5s]   \n)  / 720 / 1000 \n-\nsum_over_time(\n    sum(sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"}>0) * scalar(tarif{location=\"$Location\",type=\"einspeisung\"})/100>0)[$__range:5s]   \n)  / 720 / 1000 \n>=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "suffix:kWh" } },
   "targets": [
    {
     "expr": "max(\n sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} >0)[1d:5s] offset -1d\n )  / 720 / 1000\n)\n",
     "legendFormat": "Batteriebezug"
    },
    {
     "expr": "min(\n sum_over_time((\n    meter{location=\"$Location\",position=\"battery\",type=\"gauge\"} <0)[1d:5s] offset -1d\n )  / 720 / 1000\n) *-1\n",
     "legendFormat": "Batterieladung"
    }
   ]
  },
  {
   "title": "Batterie Spektrum ($battery kWh)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "(max_over_time(sensor{kind=\"battery\",location=\"$Location\",position=\"battery\",type=\"percent\"}[1d] offset -1d) - min_over_time(sensor{kind=\"battery\",location=\"$Location\",position=\"battery\",type=\"percent\"}[1d] offset -1d))/100*$battery",
     "legendFormat": "Batterienutzungsspektrum"
    },
    {
     "expr": "$battery - (max_over_time(sensor{kind=\"battery\",location=\"$Location\",position=\"battery\",type=\"percent\"}[1d] offset -1d) - min_over_time(sensor{kind=\"battery\",location=\"$Location\",position=\"battery\",type=\"percent\"}[1d] offset -1d))/100*$battery",
     "legendFormat": "Ungenutzt"
    }
   ]
  },
  {
   "title": "Anteil Eigenverbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 / \n(sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[$__range:5s]\n)  / 720 / 1000)\n* \n(sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[$__range])) / 1000 ) <=100 or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autarkiegrad",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time((meter{position=\"grid\",type=\"gauge\",location=\"$Location\"}< bool 20)[$__range:30m] )*100)",
     "legendFormat": "Zeit"
    },
    {
     "expr": "100-100/(\n  sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[$__range]))/1000 \n  - sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"out\",location=\"$Location\"}[$__range]))/1000\n  + sum_over_time(\n    sum(meter{location=\"$Location\",position=\"battery\",type=\"gauge\"})[$__range:5s]\n  )  / 720 / 1000\n  + sum_over_time(\n    sum(meter{location=\"$Location\",position=\"generator\",type=\"gauge\"}>0)[$__range:5s]\n  )  / 720 / 1000\n)\n*\n(\n  sum(increase(meter{position=\"grid\",type=\"counter\",direction=\"in\",location=\"$Location\"}[$__range]))/1000\n)\n\n\n",
     "legendFormat": "Energiemenge"
    }
   ]
  },
  {
   "title": "Tarif",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tarif{type=\"bezug\", location=~\"$Location\"}",
     "legendFormat": "Bezug RP"
    },
    {
     "expr": "tarif{type=\"einspeisung\", location=~\"$Location\"}",
     "legendFormat": "Einspeisung RP"
    }
   ]
  },
  {
   "title": "Innen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sensor{kind=\"indoor\",type=\"temp\", location=~\"$Location\"})",
     "legendFormat": "Temp"
    }
   ]
  }
 ]
}