#!/usr/bin/python3

import telebot
import subprocess
import sys

API_TOKEN = '<token>'
bot = telebot.TeleBot(API_TOKEN)
bot.config['api_key'] = API_TOKEN

msg = ""

for line in sys.stdin:
    msg = msg + line

bot.send_message(<chatid>, text=msg)

